{% set name = "spyder" %}
{% set version = "3.1.3" %}
{% set sha256 = "4978872cc5a006803bc8742d0a8fb43c49aef9524f0a9fcb8bd6dfcfdc2d2d6a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
    entry_points:
        - spyder = spyder.app.start:main
    number: '1'
    osx_is_app: 'True'

requirements:
  build:
    - python
    - sphinx
  run:
    - python
    - chardet >=2.0
    - jedi
    - nbconvert
    - numpydoc
    - qtawesome >=0.4.1
    - qtconsole >=4.2
    - qtpy >=1.1.0
    - pep8
    - pickleshare
    - psutil
    - pycodestyle
    - pyflakes
    - pygments >=2.0
    - pylint
    - pyqt >=5.6.0  # [osx]
    - pyqt  # [not osx]
    - rope  # [py27]
    - rope 0.9.*  # [py3k]
    - sphinx
    - pyzmq
    - python.app  # [osx]
    

test:
  commands:
    - spyder -h
  imports:
    - spyder

app:
  entry: spyder
  icon: logo.png
  summary: Scientific Python Development Environment
  type: desk

about:
  home: https://github.com/spyder-ide/spyder
  license: MIT
  license_file: LICENSE
  summary: Scientific PYthon Development EnviRonment
  description: |
    Spyder is a powerful interactive development environment for the Python
    language with advanced editing, interactive testing, debugging and
    introspection features. Additionally, Spyder is a numerical computing
    environment thanks to the support of IPython and popular Python libraries
    such as NumPy, SciPy, or matplotlib.
  doc_url: http://pythonhosted.org/spyder/
  dev_url: https://github.com/spyder-ide/spyder

extra:
  recipe-maintainers:
    - ccordoba12
    - goanpeca
