{% set name = "spyder" %}
{% set version = "3.3.1" %}
{% set sha256 = "992d74f07961df9a9b9aa495fa2d87832699ada5323850dc3e26ac0ff640b170" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    # Prevent a crash in macOS with Python 3
    - zmq.patch

build:
  number: 0
  entry_points:
    - spyder = spyder.app.start:main
  osx_is_app: True

requirements:
  build:
    - python
    - sphinx
  run:
    - python
    - pyqt 5.*
    - qtpy >=1.2.0
    - qtawesome >=0.4.1
    - rope >=0.9.4
    - pyflakes
    - jedi >=0.9
    - qtconsole >=4.2
    - pickleshare
    - nbconvert
    - pygments >=2.0
    - sphinx
    - pycodestyle
    - psutil
    - pylint
    - pyzmq
    - chardet >=2.0
    - numpydoc
    - cloudpickle
    - keyring
    - spyder-kernels 0.*
    - python.app  # [osx]

test:
  commands:
    - USER=test spyder -h  # [unix]
    - spyder -h  # [win]
  imports:
    - spyder

app:
  entry: spyder
  icon: logo.png
  summary: The Scientific Python Development Environment
  type: desk

about:
  home: https://www.spyder-ide.org/
  license: MIT
  license_file: LICENSE
  summary: The Scientific Python Development Environment
  description: |
    Spyder is a powerful scientific environment written in Python, for Python,
    and designed by and for scientists, engineers and data analysts.
    It features a unique combination of the advanced editing, analysis,
    debugging and profiling functionality of a comprehensive development tool
    with the data exploration, interactive execution, deep inspection and
    beautiful visualization capabilities of a scientific package.
    Furthermore, Spyder offers built-in integration with many popular
    scientific packages, including NumPy, SciPy, Pandas, IPython, QtConsole,
    Matplotlib, SymPy, and more.
    Beyond its many built-in features, Spyder's abilities can be extended even
    further via first- and third-party plugins.
    Spyder can also be used as a PyQt5 extension library, allowing you to build
    upon its functionality and embed its components, such as the interactive
    console or advanced editor, in your own software.
  doc_url: https://docs.spyder-ide.org/
  dev_url: https://github.com/spyder-ide/spyder

extra:
  recipe-maintainers:
    - ccordoba12
    - goanpeca
