{% set version = "6.0.5" %}
{% set python_min = "3.9" %}
{% set build = 0 %}

package:
  name: spyder-base
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/spyder/spyder-{{ version }}.tar.gz
  sha256: caa315b7009b0dd6cb55bc3d8989a15102ed785dcf793ae585f5e76dfb7a519e
  patches:
    # See spyder-ide/spyder#8316
    - osx-zmq.patch

build:
  number: {{ build }}
  entry_points:
    - spyder = spyder.app.start:main
  osx_is_app: true
  # https://github.com/conda/conda-build/issues/5385
  noarch: python  # [unix]
  string: "osx_pyh{{ PKG_HASH }}_{{ PKG_BUILDNUM }}"    # [osx]
  string: "linux_pyh{{ PKG_HASH }}_{{ PKG_BUILDNUM }}"  # [linux]

requirements:
  build:
    - python >={{ python_min }}           # [unix and (build_platform != target_platform)]
    - python                              # [win  and (build_platform != target_platform)]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
  host:
    - python {{ python_min }}  # [unix]
    - python                   # [win]
    - pip
    - setuptools
    - packaging
  run:
    - python >={{ python_min }}  # [unix]
    - python                     # [win]
    - aiohttp >=3.9.3
    - applaunchservices >=0.3.0  # [osx]
    - asyncssh >=2.14.0,<3.0.0
    - atomicwrites >=1.2.0
    - chardet >=2.0.0
    - cloudpickle >=0.5.0
    - cookiecutter >=1.6.0
    - diff-match-patch >=20181111
    - fcitx-qt5 >=1.2.7  # [linux]
    - fzf >=0.42.0
    - importlib-metadata >=4.6.0
    - intervaltree >=3.0.2
    - ipython >=8.12.2,<9.0.0,!=8.17.1
    - jedi >=0.17.2,<0.20.0
    - jellyfish >=0.7
    - jsonschema >=3.2.0
    - keyring >=17.0.0
    - nbconvert >=4.0
    - numpydoc >=0.6.0
    - parso >=0.7.0,<0.9.0
    - pexpect >=4.4.0
    - pickleshare >=0.4
    - psutil >=5.3
    # This is here to work around a bug in mamba
    - ptyprocess >=0.5  # [win]
    - pygithub >=2.3.0
    - pygments >=2.0
    - pylint >=3.1,<4
    - pylint-venv >=3.0.2
    - pyls-spyder >=0.4.0
    - python.app  # [osx]
    - python-lsp-black >=2.0.0,<3.0.0
    - python-lsp-server >=1.12.0,<1.13.0
    - pyuca >=1.2
    - pyxdg >=0.26  # [linux]
    - pyzmq >=24.0.0
    - qdarkstyle >=3.2.0,<3.3.0
    - qstylizer >=0.2.2
    - qtawesome >=1.4.0,<1.5.0
    - qtconsole-base >=5.6.1,<5.7.0
    - qtpy >=2.4.0
    - rtree >=0.9.7
    - setuptools >=49.6.0
    - sphinx >=0.6.6
    - spyder-kernels >=3.0.3,<3.1.0
    - superqt >=0.6.2,<1.0.0
    - textdistance >=4.2.0
    - three-merge >=0.1.1
    - watchdog >=0.10.3
    - yarl >=1.9.4
    # https://conda-forge.org/docs/maintainer/knowledge_base/#noarch-python
    - __linux  # [linux]
    - __osx    # [osx]
  run_constrained:
    - menuinst >=2.1.2
    - spyder =={{ version }}=*{{ build }}

test:
  requires:
    - python {{ python_min }} # [unix]
    - python  # [not unix]
    - pip
  commands:
    - spyder -h
    - python -m pip check
  imports:
    - spyder

app:
  entry: spyder
  icon: spyder.png
  summary: The Scientific Python Development Environment
  type: desk

outputs:
  - name: spyder-base
  - name: spyder
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - spyder-base =={{ version }}=*{{ build }}
        - pyqt >=5.15,<5.16
        - pyqtwebengine >=5.15,<5.16
        - qtconsole >=5.6.1,<5.7.0
    test:
      requires:
        - python {{ python_min }} # [unix]
        - python  # [not unix]
        - pip
      commands:
        - spyder -h
        - python -m pip check
      imports:
        - spyder

about:
  home: https://www.spyder-ide.org/
  license: MIT
  license_file: LICENSE.txt
  summary: The Scientific Python Development Environment
  description: |
    Spyder is a powerful scientific environment written in Python, for Python,
    and designed by and for scientists, engineers and data analysts.
    It features a unique combination of the advanced editing, analysis,
    debugging and profiling functionality of a comprehensive development tool
    with the data exploration, interactive execution, deep inspection and
    beautiful visualization capabilities of a scientific package.\n
    Furthermore, Spyder offers built-in integration with many popular
    scientific packages, including NumPy, SciPy, Pandas, IPython, QtConsole,
    Matplotlib, SymPy, and more.\n
    Beyond its many built-in features, Spyder can be extended even further via
    third-party plugins.\n
    Spyder can also be used as a PyQt5 extension library, allowing you to build
    upon its functionality and embed its components, such as the interactive
    console or advanced editor, in your own software.
  doc_url: https://docs.spyder-ide.org/
  dev_url: https://github.com/spyder-ide/spyder

extra:
  feedstock-name: spyder
  recipe-maintainers:
    - ccordoba12
    - dalthviz
    - mrclary
