{% set version = "5.5.3" %}

package:
  name: spyder
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/spyder/spyder-{{ version }}.tar.gz
  sha256: 8b738429b8842df12681f7f71107ebeb119cef87f590cc757be3db6d7a6b922b
  patches:
    # See spyder-ide/spyder#8316
    - osx-zmq.patch

build:
  number: 0
  skip: true  # [osx and arm64 and py < 39]
  entry_points:
    - spyder = spyder.app.start:main
  osx_is_app: true

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - applaunchservices >=0.3.0  # [osx]
    - atomicwrites >=1.2.0
    - chardet >=2.0.0
    - cloudpickle >=0.5.0
    - cookiecutter >=1.6.0
    - diff-match-patch >=20181111
    - intervaltree >=3.0.2
    - ipython >=8.12.2,<9.0.0,!=8.17.1
    - jedi >=0.17.2,<0.20.0
    - jellyfish >=0.7
    - jsonschema >=3.2.0
    - keyring >=17.0.0
    - nbconvert >=4.0
    - numpydoc >=0.6.0
    - paramiko >=2.4.0  # [win]
    - parso >=0.7.0,<0.9.0
    - pexpect >=4.4.0
    - pickleshare >=0.4
    # This is here to work around a bug in mamba
    - ptyprocess >=0.5  # [win]
    - psutil >=5.3
    - pygments >=2.0
    - pylint >=2.5.0,<3.1
    - pylint-venv >=3.0.2
    - pyls-spyder >=0.4.0
    - pyqt >=5.10,<5.16
    - pyqtwebengine >=5.10,<5.16
    - python.app  # [osx]
    - python-lsp-black >=2.0.0,<3.0.0
    - python-lsp-server >=1.10.0,<1.11.0
    - pyxdg >=0.26  # [linux]
    - pyzmq >=22.1.0
    - qdarkstyle >=3.2.0,<3.3.0
    - qstylizer >=0.2.2
    - qtawesome >=1.2.1,<1.3.0
    - qtconsole >=5.5.1,<5.6.0
    - qtpy >=2.1.0
    - rtree >=0.9.7
    - setuptools >=49.6.0
    - sphinx >=0.6.6
    - spyder-kernels >=2.5.1,<2.6.0
    - textdistance >=4.2.0
    - three-merge >=0.1.1
    - watchdog >=0.10.3
  run_constrained:
    - menuinst >=1.4.17

test:
  requires:
    - pip
  commands:
    - USER=test spyder -h  # [unix]
    - spyder -h  # [win]
    # Pip fails when running but the package is installed correctly
    - python -m pip check  # [not aarch64]
  imports:
    - spyder

app:
  entry: spyder
  icon: logo.png
  summary: The Scientific Python Development Environment
  type: desk

about:
  home: https://www.spyder-ide.org/
  license: MIT
  license_file: LICENSE.txt
  summary: The Scientific Python Development Environment
  description: |
    Spyder is a powerful scientific environment written in Python, for Python,
    and designed by and for scientists, engineers and data analysts.
    It features a unique combination of the advanced editing, analysis,
    debugging and profiling functionality of a comprehensive development tool
    with the data exploration, interactive execution, deep inspection and
    beautiful visualization capabilities of a scientific package.\n
    Furthermore, Spyder offers built-in integration with many popular
    scientific packages, including NumPy, SciPy, Pandas, IPython, QtConsole,
    Matplotlib, SymPy, and more.\n
    Beyond its many built-in features, Spyder can be extended even further via
    third-party plugins.\n
    Spyder can also be used as a PyQt5 extension library, allowing you to build
    upon its functionality and embed its components, such as the interactive
    console or advanced editor, in your own software.
  doc_url: https://docs.spyder-ide.org/
  dev_url: https://github.com/spyder-ide/spyder

extra:
  recipe-maintainers:
    - ccordoba12
    - dalthviz
    - andfoy
    - steff456
