{% set version = "5.2.2" %}

package:
  name: spyder
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/spyder/spyder-{{ version }}.tar.gz
  sha256: dc322291096c73b3ed6a08bc75d47989afaedb8757781769a519089ffc69ddb8
  patches:
    # See spyder-ide/spyder#8316
    - osx-zmq.patch

build:
  number: 3
  entry_points:
    - spyder = spyder.app.start:main
  osx_is_app: true

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - applaunchservices >=0.1.7  # [osx]
    - atomicwrites >=1.2.0
    - chardet >=2.0.0
    - cloudpickle >=0.5.0
    - cookiecutter >=1.6.0
    - diff-match-patch >=20181111
    - intervaltree >=3.0.2
    - ipython >=7.6.0,<8.0.0
    - jedi >=0.17.2,<0.19.0
    - jellyfish >=0.7
    - jsonschema >=3.2.0
    - keyring >=17.0.0
    - nbconvert >=4.0
    - numpydoc >=0.6.0
    - paramiko >=2.4.0  # [win]
    - parso >=0.7.0,<0.9.0
    - pexpect >=4.4.0
    - pickleshare >=0.4
    # This is here to work around a bug in mamba
    - ptyprocess >=0.5  # [win]
    - psutil >=5.3
    - pygments >=2.0
    - pylint >=2.5.0
    - python-lsp-black >=1.0.0
    - pyls-spyder >=0.4.0
    - pyqt >=5.6,<5.16
    - python.app  # [osx]
    - python-lsp-server >=1.3.2,<1.4.0
    - pyxdg >=0.26  # [linux]
    - pyzmq >=17
    - qdarkstyle 3.0.2
    - qstylizer >=0.1.10
    - qtawesome >=1.0.2
    - qtconsole >=5.2.1,<5.3.0
    - qtpy >=1.5.0
    - rtree >=0.9.7
    - setuptools >=49.6.0
    - sphinx >=0.6.6
    - spyder-kernels >=2.2.1,<2.3.0
    - textdistance >=4.2.0
    - three-merge >=0.1.1
    - watchdog >=0.10.3
  run_constrained:
    - menuinst >=1.4.17

test:
  requires:
    - pip
    - jinja2 <3.1 # numpydoc has this as a runtime version check
  commands:
    - USER=test spyder -h  # [unix]
    - spyder -h  # [win]
    - python -m pip check  # [linux or win]
  imports:
    - spyder

app:
  entry: spyder
  icon: logo.png
  summary: The Scientific Python Development Environment
  type: desk

about:
  home: https://www.spyder-ide.org/
  license: MIT
  license_file: LICENSE.txt
  summary: The Scientific Python Development Environment
  description: |
    Spyder is a powerful scientific environment written in Python, for Python,
    and designed by and for scientists, engineers and data analysts.
    It features a unique combination of the advanced editing, analysis,
    debugging and profiling functionality of a comprehensive development tool
    with the data exploration, interactive execution, deep inspection and
    beautiful visualization capabilities of a scientific package.\n
    Furthermore, Spyder offers built-in integration with many popular
    scientific packages, including NumPy, SciPy, Pandas, IPython, QtConsole,
    Matplotlib, SymPy, and more.\n
    Beyond its many built-in features, Spyder can be extended even further via
    third-party plugins.\n
    Spyder can also be used as a PyQt5 extension library, allowing you to build
    upon its functionality and embed its components, such as the interactive
    console or advanced editor, in your own software.
  doc_url: https://docs.spyder-ide.org/
  dev_url: https://github.com/spyder-ide/spyder

extra:
  recipe-maintainers:
    - ccordoba12
    - dalthviz
    - andfoy
    - steff456
