{% set name = "spyder" %}
{% set version = "3.2.8" %}
{% set sha256 = "e56d83875d725c16646338a3769fe1a5e4450c825e207127f85eedbe845f8c47" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    # Prevent a crash in macOS with Python 3
    - zmq.patch

build:
  number: 0
  entry_points:
    - spyder = spyder.app.start:main
  osx_is_app: True

requirements:
  build:
    - python
    - sphinx
  run:
    - python
    - pyqt
    - qtpy >=1.2.0
    - qtawesome >=0.4.1
    - rope >=0.9.4
    - pyflakes
    - jedi >=0.9
    - qtconsole >=4.2
    - pickleshare
    - nbconvert
    - pygments >=2.0
    - sphinx
    - pycodestyle
    - psutil
    - pylint
    - pyzmq
    - chardet >=2.0
    - numpydoc
    - cloudpickle
    - python.app  # [osx]

test:
  commands:
    - USER=test spyder -h  # [unix]
    - spyder -h  # [win]
  imports:
    - spyder

app:
  entry: spyder
  icon: logo.png
  summary: Scientific Python Development Environment
  type: desk

about:
  home: https://github.com/spyder-ide/spyder
  license: MIT
  license_file: LICENSE
  summary: Scientific PYthon Development EnviRonment
  description: |
    Spyder is a powerful interactive development environment for the Python
    language with advanced editing, interactive testing, debugging and
    introspection features. Additionally, Spyder is a numerical computing
    environment thanks to the support of IPython and popular Python libraries
    such as NumPy, SciPy, or matplotlib.
  doc_url: http://pythonhosted.org/spyder/
  dev_url: https://github.com/spyder-ide/spyder

extra:
  recipe-maintainers:
    - ccordoba12
    - goanpeca
