{% set version = "4.1.2" %}

package:
  name: spyder
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/spyder/spyder-{{ version }}.tar.gz
  sha256: eef7edfeb6fc93cf7cd7cad7dca93c138340b75636d9e81724fdcf9e74d6d163
  patches:
    # See spyder-ide/spyder#8316
    - osx-zmq.patch

build:
  number: 0
  entry_points:
    - spyder = spyder.app.start:main
  osx_is_app: true

requirements:
  host:
    - python
    - pip
  run:
    - python
    - applaunchservices >=0.1.7  # [osx]
    - atomicwrites >=1.2.0
    - chardet >=2.0.0
    - cloudpickle >=0.5.0
    - diff-match-patch >=20181111
    - intervaltree
    - jedi 0.15.2
    - keyring  # [not (linux and py2k)]
    - nbconvert >=4.0
    - numpydoc >=0.6.0
    - paramiko >=2.4.0  # [win]
    - parso 0.5.2
    - pexpect >=4.4.0
    - pickleshare >=0.4
    - psutil >=5.3
    - pygments >=2.0
    - pylint >=0.25
    - pyqt >=5.6,<5.13
    - python.app  # [osx]
    - python-language-server >=0.31.9,<0.32.0
    - pyxdg >=0.26  # [linux]
    - pyzmq >=17
    - qdarkstyle >=2.8
    - qtawesome >=0.5.7
    - qtconsole >=4.6.0
    - qtpy >=1.5.0
    - rtree >=0.8.3
    - sphinx >=0.6.6
    - spyder-kernels >=1.9.0,<1.10.0
    - watchdog

test:
  commands:
    - USER=test spyder -h  # [unix]
    - spyder -h  # [win]
  imports:
    - spyder

app:
  entry: spyder
  icon: logo.png
  summary: The Scientific Python Development Environment
  type: desk

about:
  home: https://www.spyder-ide.org/
  license: MIT
  license_file: LICENSE.txt
  summary: The Scientific Python Development Environment
  description: |
    Spyder is a powerful scientific environment written in Python, for Python,
    and designed by and for scientists, engineers and data analysts.
    It features a unique combination of the advanced editing, analysis,
    debugging and profiling functionality of a comprehensive development tool
    with the data exploration, interactive execution, deep inspection and
    beautiful visualization capabilities of a scientific package.\n
    Furthermore, Spyder offers built-in integration with many popular
    scientific packages, including NumPy, SciPy, Pandas, IPython, QtConsole,
    Matplotlib, SymPy, and more.\n
    Beyond its many built-in features, Spyder can be extended even further via
    third-party plugins.\n
    Spyder can also be used as a PyQt5 extension library, allowing you to build
    upon its functionality and embed its components, such as the interactive
    console or advanced editor, in your own software.
  doc_url: https://docs.spyder-ide.org/
  dev_url: https://github.com/spyder-ide/spyder

extra:
  recipe-maintainers:
    - ccordoba12
    - goanpeca
