appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: kgKRFdFrJB8HKAgBlSyVBmeyLLnwTvbs4VPB94gOSCpEv63NjWdbnFgnD7sQOHHFZ5+YXxhQOrdsrcD9SX1N0RYnSYFg96GWoNMA8/RW7tvhsE0hEijzUwq4Gxi2JFGCIBsS0uqLzXKd6x3dZs6kNxmllsPROxDYmWi8/F9LARych47XBJC1ah4JF4Ksky8/Qh1ho7fZ+Plb5EfOD1sFkQBAxFeuY6/CTIhaS8R1h6sxXyfoX9DmGSGZyofj398+5/ibHcqdH0pl0PXSf8oBr8BKk7HR+D6lHaOAYCNoJeI9H8DJEdjCDFdU7Ml2kRb36kBSjSjenjdcwian44R6QF81X39L2Kc+3+p9JkDAJJd8pzeS99yE/rt1LLyCa5zU0f3dkAdvQpQvZ7p2D3//NROEAzYE3T3HjWsUeZZ6c+di4wXCOOc3Kl02FuceyFKsegyus+fqZBWL5uHsAwh5Hn9AjkPeC36wpcmUIDP/AJCxCyW4h6pq7tsUUmsqWDE2oxJEUxYA/wOPn8tGh2txQnVDFDYz7Kk0T+ZHEuYAC0gBaGpIhbu1RvYyttKXgPNnuvQO51kAG5M6rhKDPDsimBTf8dSYzHj4WS1rm68RhQhPXoU/v4Q3CfdsUJDJ2cQWQgreSU950Xbfbw8bynEuCmmMsMKKB6NjpeB5d6zKnf0=}
