bot:
  inspection: disabled
build_platform:
  linux_aarch64: linux_64
  osx_arm64: osx_64
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
# We have to set this otherwise we get an error when trying to actually spin up the GUI,
# probably related to how pyqt-feedstock is built on cos7. PySide6 is also built on cos7.
os_version:
  linux_64: cos7
provider:
  linux_aarch64: default
  win: azure
test: native_and_emulated
noarch_platforms:
  - linux_64
  - osx_64
azure:
  store_build_artifacts: True
