bot:
  inspection: disabled
build_platform:
  linux_aarch64: linux_64
  osx_arm64: osx_64
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux_aarch64: default
  win: azure
test: native_and_emulated
noarch_platforms:
  - linux_64
  - osx_64
azure:
  store_build_artifacts: True
# Prevent package upload failure due to anaconda-client 1.13.0 build 0 missing pillow as dependency
# See https://github.com/conda-forge/anaconda-client-feedstock/issues/57 and https://github.com/conda-forge/jupyterlab-feedstock/pull/470
remote_ci_setup:
  - conda-forge-ci-setup=4
  - conda-build>=24.1
  - anaconda-client>=1.13.0=pyh29332c3_1